# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

group_imports = "One"
imports_granularity = "Crate"
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = false
